Update TWRP-Recovery-Pie.yml

diff --git a/.github/workflows/TWRP-Recovery-Pie.yml b/.github/workflows/TWRP-Recovery-Pie.yml
--- a/.github/workflows/TWRP-Recovery-Pie.yml
+++ b/.github/workflows/TWRP-Recovery-Pie.yml
@@ -217,9 +217,9 @@ jobs:
     - name: Building Image 
       run: |
         cd workspace
-        [[ -e ./build/make/core/Makefile ]] && [[ -e ./${{ github.event.inputs.DEVICE_PATH }}/scripts/mkimage ]] && sudo chmod 0755 ./${{ github.event.inputs.DEVICE_PATH }}/scripts/mkimage && sed -i '1525a \\t$(hide) $(CURDIR)/device/alps/tb8163p3_bsp/scripts/mkimage $@ $(CURDIR)/device/alps/tb8163p3_bsp/scripts/mtk_ramdisk.cfg > $@.mtk && mv -vf $@.mtk $@' ./build/make/core/Makefile && \
-          grep -q "mtk_ramdisk.cfg" ./build/make/core/Makefile && \
-          echo -e "\nChange verified!" || echo -e "\nEdit failed: string not found.";
+        # [[ -e ./build/make/core/Makefile ]] && [[ -e ./${{ github.event.inputs.DEVICE_PATH }}/scripts/mkimage ]] && sudo chmod 0755 ./${{ github.event.inputs.DEVICE_PATH }}/scripts/mkimage && sed -i '1525a \\t$(hide) $(CURDIR)/device/alps/tb8163p3_bsp/scripts/mkimage $@ $(CURDIR)/device/alps/tb8163p3_bsp/scripts/mtk_ramdisk.cfg > $@.mtk && mv -vf $@.mtk $@' ./build/make/core/Makefile && \
+        #  grep -q "mtk_ramdisk.cfg" ./build/make/core/Makefile && \
+        #  echo -e "\nChange verified!" || echo -e "\nEdit failed: string not found.";
         source build/envsetup.sh
         export ALLOW_MISSING_DEPENDENCIES=true
         lunch ${{ env.DEVICE_MAKEFILE }}-eng && make clean && make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
