Update TWRP-Builder.yml

diff --git a/.github/workflows/TWRP-Builder.yml b/.github/workflows/TWRP-Builder.yml
--- a/.github/workflows/TWRP-Builder.yml
+++ b/.github/workflows/TWRP-Builder.yml
@@ -119,7 +119,7 @@ jobs:
         mkdir -p ${GITHUB_WORKSPACE}/workspace/kernel/alps/tb8163p3_bsp
         set -o allexport
         export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
-        # export TARGET_FORCE_PREBUILT_KERNEL=true
+        export TARGET_FORCE_PREBUILT_KERNEL=true
         echo "PREBUILT_KERNEL=true" >> $GITHUB_ENV
         if [[ `which git` ]]; then
           echo -e "\n`git --version`\n";
@@ -183,7 +183,7 @@ jobs:
         fi
         export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
         git config --global --add safe.directory .
-        cd kernel/alps/tb8163p3_bsp
+        [[ -d ./kernel/alps/tb8163p3_bsp ]] && cd kernel/alps/tb8163p3_bsp || [[ -d ./"${{ github.event.inputs.DEVICE_PATH }}" ]] && cd "${{ github.event.inputs.DEVICE_PATH }}"
         calculatedSha=$(git rev-parse --short ${{ github.sha }})
         echo "COMMIT ID: $calculatedSha"
         echo "COMMIT_ID=$calculatedSha" >> $GITHUB_ENV
@@ -192,10 +192,10 @@ jobs:
       
     - name: Prepare The Environment
       run: |
-        sudo apt-get update
-        sudo apt-get -yq full-upgrade
-        ${{ inputs.CLEAN_ENVIRONMENT == 'true' }} && sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install build-essential remake ccache g++ git git-core libgmp-dev libmpfr-dev libmpc-dev gnupg flex bison zip curl zlib1g-dev libc6-dev-i386 unzip fontconfig bc repo m4 libssl-dev kmod device-tree-compiler libx11-dev lib32z1-dev git-lfs libelf-dev libxml2 rsync adb fastboot ncurses-doc libasound2-doc gnome-shell lib32stdc++6-10-dbg libx32stdc++6-10-dbg wx3.0-doc gettext distcc gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib lib32ncurses5-dev x11proto-core-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libgflags-dev python3 tree 
-        sudo apt-get -yq dist-upgrade
+        sudo apt-get update >/dev/null
+        # sudo apt-get -yq full-upgrade
+        sudo DEBIAN_FRONTEND=noninteractive apt-get -y -q -q install build-essential remake ccache g++ git git-core libgmp-dev libmpfr-dev libmpc-dev gnupg flex bison zip curl zlib1g-dev libc6-dev-i386 unzip fontconfig bc repo m4 libssl-dev kmod device-tree-compiler libx11-dev lib32z1-dev git-lfs libelf-dev libxml2 rsync adb fastboot ncurses-doc libasound2-doc gnome-shell lib32stdc++6-10-dbg libx32stdc++6-10-dbg wx3.0-doc gettext distcc gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib lib32ncurses5-dev x11proto-core-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libgflags-dev python3 tree >/dev/null;
+        sudo apt-get -yq dist-upgrade >/dev/null
         sudo add-apt-repository universe
         sudo apt-get -yq install libncurses5 libtinfo5
         sudo mkdir -p /usr/local/lib/android/sdk
@@ -255,7 +255,7 @@ jobs:
       run: |
         sudo apt-get -yq install python2 >/dev/null
         cd /usr/bin
-        sudo ln -sf python2 python
+        sudo ln -svf python2 python
       continue-on-error: true
 
     - name: Save Workspace
@@ -317,42 +317,42 @@ jobs:
      # export EXTRA_CMDS='bootopt=64S3,32N2,32N2 androidboot.selinux=permissive androidboot.init_fatal_reboot_target=recovery console=ttyS0,921600n1 root=/dev/ram androidboot.hardware=mt8163 firmware_class.path=/vendor/firmware build=06_12_24(gA1A470FC) lcm_id=4000 brightness=8388613 avdd=52 vcom=46 skip_initramfs ro rootwait init=/init root=PARTUUID=e7099731-95a6-45a6-a1e5-1b6aba032cf1 androidboot.verifiedbootstate=orange androidboot.atm=disabled androidboot.meta_log_disable=0 androidboot.dtbo_idx=0 printk.disable_uart=0 bootprof.pl_t=1680 bootprof.lk_t=7245 boot_reason=4 androidboot.serialno=SC5SKNLBEYIRBMR4 androidboot.bootreason=reboot mrdump_ddrsv=yes mrdump_rsvmem=0x56000000,0x400000,0x42000000,0x17f740,0x54000000,0x80000'
     - name: Export Build Settings
       run: |
-        set -o allexport
-        echo 'export ARCH=arm' | sudo tee -a ~/.bashrc >/dev/null;
-        echo 'export LC_ALL=C' | sudo tee -a ~/.bashrc >/dev/null;
-        echo 'export USE_NINJA=true' | sudo tee -a ~/.bashrc >/dev/null;
-        echo 'export ALLOW_MISSING_DEPENDENCIES=true' | sudo tee -a ~/.bashrc >/dev/null;
-        echo 'export LLVM_ENABLE_THREADS=ON' | sudo tee -a ~/.bashrc >/dev/null;
-        echo 'export BOARD_VNDK_RUNTIME_DISABLE=true' | sudo tee -a ~/.bashrc >/dev/null;
-        echo 'export GIT_DISCOVERY_ACROSS_FILESYSTEM=1' | sudo tee -a ~/.bashrc >/dev/null;
-        # echo 'export TARGET_FORCE_PREBUILT_KERNEL=true' | sudo tee -a ~/.bashrc >/dev/null;
+        # set -o allexport
+          echo 'export ARCH=arm' | sudo tee -a ~/.bashrc >/dev/null;
+          echo 'export LC_ALL=C' | sudo tee -a ~/.bashrc >/dev/null;
+          # echo 'export USE_NINJA=true' | sudo tee -a ~/.bashrc >/dev/null;
+          echo 'export ALLOW_MISSING_DEPENDENCIES=true' | sudo tee -a ~/.bashrc >/dev/null;
+          echo 'export LLVM_ENABLE_THREADS=ON' | sudo tee -a ~/.bashrc >/dev/null;
+          echo 'export BOARD_VNDK_RUNTIME_DISABLE=true' | sudo tee -a ~/.bashrc >/dev/null;
+          echo 'export GIT_DISCOVERY_ACROSS_FILESYSTEM=1' | sudo tee -a ~/.bashrc >/dev/null;
+          # echo 'export TARGET_FORCE_PREBUILT_KERNEL=true' | sudo tee -a ~/.bashrc >/dev/null;
           # sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq linux-headers-$(uname -r) >/dev/null 2>&1;
-          export BRANCH=android-9.0
-          export CPU_SSE42=false
+          # export BRANCH=android-9.0
+          # export CPU_SSE42=false
           # export DEBUG_KERNEL=y
           # export CLANG_TRIPLE=arm-linux-gnu-
           # export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
           # export DEFCONFIG=tb8163p3_bsp_defconfig
           # export KERNEL_DIR=kernel/alps/tb8163p3_bsp
           # export LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN=prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin
-          export FILES="arch/arm/boot/zImage vmlinux System.map"
-          export STOP_SHIP_TRACEPRINTK=1
-          export CONFIG_INIT_ENV_ARG_LIMIT=32
-          export CROSS_COMPILE="arm-eabi-"
-          export CONFIG_FS_ENCRYPTION=N
-          export CONFIG_DEBUG_SECTION_MISMATCH=y
-          #export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
-          export C_COMPILER_NAME=clang
-          export CXX_COMPILER_NAME=clang++
-          export COMPILER_VERSION=12
-          export CC=$C_COMPILER_NAME-$COMPILER_VERSION
-          export CXX=$CXX_COMPILER_NAME-$COMPILER_VERSION
-          alias compiler=$C_COMPILER_NAME
-          alias compiler.version=$COMPILER_VERSION
-          alias compiler.libcxx=libstdc*
-          alias std=c++17
-          alias cc=$CC
-          alias c++="$CXX -O2 -W -Wall -std=$std"
+          # export FILES="arch/arm/boot/zImage vmlinux System.map"
+          # export STOP_SHIP_TRACEPRINTK=1
+          # export CONFIG_INIT_ENV_ARG_LIMIT=32
+          # export CROSS_COMPILE="arm-eabi-"
+          # export CONFIG_FS_ENCRYPTION=N
+          # export CONFIG_DEBUG_SECTION_MISMATCH=y
+          # export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
+          # export C_COMPILER_NAME=clang
+          # export CXX_COMPILER_NAME=clang++
+          # export COMPILER_VERSION=12
+          # export CC=$C_COMPILER_NAME-$COMPILER_VERSION
+          # export CXX=$CXX_COMPILER_NAME-$COMPILER_VERSION
+          # alias compiler=$C_COMPILER_NAME
+          # alias compiler.version=$COMPILER_VERSION
+          # alias compiler.libcxx=libstdc*
+          # alias std=c++17
+          # alias cc=$CC
+          # alias c++="$CXX -O2 -W -Wall -std=$std"
           avb=$(find $GITHUB_WORKSPACE -path '*/external/avb/*' -type f -name 'avbtool' | head -n 1);
           if [[ -f "$avb" ]]; then
             # sed -i 's/2L\*\*/2\*\*/g' "$avb";
@@ -362,7 +362,9 @@ jobs:
             sed -i '1s|.*|#!/usr/bin/env python2|' "$avb";
             echo "Forced avbtool to use Python 2 at: $avb";
           fi;
-          [[ -e ./build/make/core/Makefile ]] && [[ -e ./device/alps/tb8163p3_bsp/scripts/mkimage ]] && sed -i '1525a \\t$(hide) $(CURDIR)/device/alps/tb8163p3_bsp/scripts/mkimage $@ $(CURDIR)/device/alps/tb8163p3_bsp/scripts/mtk_ramdisk.cfg > $@.mtk && mv -vf $@.mtk $@' $gitbase/build/make/core/Makefile
+          [[ -e ./build/make/core/Makefile ]] && [[ -e ./device/alps/tb8163p3_bsp/scripts/mkimage ]] && sed -i '1525a \\t$(hide) $(CURDIR)/device/alps/tb8163p3_bsp/scripts/mkimage $@ $(CURDIR)/device/alps/tb8163p3_bsp/scripts/mtk_ramdisk.cfg > $@.mtk && mv -vf $@.mtk $@' $gitbase/build/make/core/Makefile && \
+          grep -q "mtk_ramdisk.cfg" $gitbase/build/make/core/Makefile && \
+          echo -e "\nChange verified!" || echo -e "\nEdit failed: string not found.";
           source_64=$(find $GITHUB_WORKSPACE -path '*/arch/arm64/*' -type f -name 'tb8163p3_64_k49.dts' | head -n 1);
           target_dir=$(find $GITHUB_WORKSPACE -path '*/arch/arm/*' -type d -name 'dts' | head -n 1);
           if [[ -f "$source_64" && -d "$target_dir" ]]; then
